version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.8/29 # 192.168.1.9 - 192.168.1.14 ?

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - unbound
    network_mode: "host"
    dns:
      - 192.168.1.11 # Points to unbound
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: ""
      FTLCONF_LOCAL_IPV4: 192.168.1.10 # Internal IP of pihole
      DNS1: 192.168.1.11 # Unbound IP
      DNS2: 192.168.1.11 # If we don't specify two, it will auto pick google.
    # Volumes store your data between container upgrades
    volumes:
      - './config/pihole/etc/pihole:/etc/pihole'
      - './config/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: "klutchell/unbound:latest"
    volumes:
      - ./config/unbound/unbound.conf:/etc/unbound/custom.conf.d/unbound.conf
    networks:
      private_network:
        ipv4_address: 192.168.1.11
    restart: unless-stopped

  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi-controller
    environment:
      - MEM_LIMIT=1024
    volumes:
      - ./config/unifi-controller:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - TZ=Europe/London
      - SERVERURL=10.241.215.247 # zerotier
      - SERVERPORT=12345 #optional
      - PEERS=ax1800 #optional
      - PEERDNS=10.241.215.247 # pihole running on network mode host
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config/wireguard:/config
      - /lib/modules:/lib/modules #optional
    ports:
      - 12345:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped